"""H1 — Semántica de prioridad de modlist.txt de Mod Organizer 2.

Valida y congela la relación contractual entre el formato físico en disco de MO2
y la representación interna normalizada de Sky-Claw:

1. FORMATO FÍSICO EN DISCO (MO2):
   ``Profile::doWriteModlist`` recorre ``m_ModIndexByPriority`` en reversa
   (``crbegin()`` a ``crend()``), por lo que en disco:
   - Primera línea habilitada (``+Nombre``) = MAYOR prioridad.
   - Última línea habilitada = MENOR prioridad.

2. NORMALIZACIÓN CENTRAL EN EL BOUNDARY (read_enabled_mods):
   ``read_enabled_mods()`` invierte ese orden al leer (``tuple(reversed(enabled))``)
   para que la representación interna consumida por todo el resto de Sky-Claw sea
   estrictamente CRECIENTE:
   - Índice 0 = menor prioridad.
   - Último índice = mayor prioridad (convención "último gana").

3. CONSUMIDORES UNIFICADOS:
   - ``mod_effectivity.py`` (los superiores son ``enabled[indice + 1 :]``).
   - ``vfs_attestation.py`` (selección de canaries con overwrite y superiores).
   - ``asset_scanner.py`` (delega en ``read_enabled_mods``).
"""

from __future__ import annotations

import ast
import pathlib

import pytest

from sky_claw.local.assets.asset_scanner import AssetConflictDetector
from sky_claw.local.mo2.mod_effectivity import ModEffectivityError, verificar_artifact_efectivo
from sky_claw.local.mo2.vfs_attestation import (
    VfsAttestationError,
    build_attestation_challenge,
    build_attestation_challenge_for_source,
    read_enabled_mods,
)


def test_golden_real_mo2_modlist_format(tmp_path: pathlib.Path) -> None:
    """TEST GOLDEN: fixture realista con el formato exacto en disco que escribe MO2.

    En modlist.txt, la primera línea habilitada es la de mayor prioridad.
    read_enabled_mods() devuelve la tupla en orden de prioridad creciente
    (menor a mayor).
    """
    modlist = tmp_path / "modlist.txt"
    modlist.write_text(
        "# This file was automatically generated by Mod Organizer.\r\n"
        "+HighPriorityMod\r\n"
        "+TexGen Output\r\n"
        "+LowPriorityMod\r\n"
        "*separator_Textures\r\n"
        "-DisabledMod\r\n",
        encoding="utf-8-sig",
    )

    resultado = read_enabled_mods(modlist)
    assert resultado == ("LowPriorityMod", "TexGen Output", "HighPriorityMod")


def test_h1_a_effectivity(tmp_path: pathlib.Path) -> None:
    """TEST H1-A: efecto de la prioridad sobre el gate de efectividad del artifact.

    Escenario:
    High > TexGen Output > Low (en modlist.txt real: High primero, TexGen en medio, Low después).
    - Mismo path en Low con bytes diferentes: Low NO eclipsa TexGen Output.
    - Mismo path en High con bytes diferentes: High SÍ eclipsa TexGen Output -> BLOCK.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+High\n+TexGen Output\n+Low\n", encoding="utf-8")

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "test.dds").write_bytes(b"AUTHORIZED_TEXGEN")

    low_dir = mods_dir / "Low" / "textures"
    low_dir.mkdir(parents=True)
    (low_dir / "test.dds").write_bytes(b"LOW_BYTES_DIFFERENT")

    high_dir = mods_dir / "High" / "textures"
    high_dir.mkdir(parents=True)

    enabled = read_enabled_mods(modlist)
    assert enabled == ("Low", "TexGen Output", "High")

    # Paso 1: Low tiene bytes diferentes pero prioridad inferior: NO eclipsa
    total = verificar_artifact_efectivo(
        artifact_root=artifact_root,
        mod_name="TexGen Output",
        mods_dir=mods_dir,
        data_root=data_root,
        enabled=enabled,
    )
    assert total == 1

    # Paso 2: High tiene bytes diferentes y prioridad superior: SÍ eclipsa -> BLOCK
    (high_dir / "test.dds").write_bytes(b"HIGH_BYTES_DIFFERENT")
    with pytest.raises(ModEffectivityError, match="High"):
        verificar_artifact_efectivo(
            artifact_root=artifact_root,
            mod_name="TexGen Output",
            mods_dir=mods_dir,
            data_root=data_root,
            enabled=enabled,
        )


def test_h1_b_identical_higher_override(tmp_path: pathlib.Path) -> None:
    """TEST H1-B: mod de mayor prioridad con bytes idénticos NO bloquea efectividad.

    Preserva la propiedad de defense-in-depth: si un mod superior provee
    exactamente los mismos bytes del artifact, el contenido efectivo bajo USVFS
    sigue siendo el autorizado.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+High\n+TexGen Output\n+Low\n", encoding="utf-8")

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "diffuse.dds").write_bytes(b"EXACT_BYTES")

    high_dir = mods_dir / "High" / "textures"
    high_dir.mkdir(parents=True)
    (high_dir / "diffuse.dds").write_bytes(b"EXACT_BYTES")

    enabled = read_enabled_mods(modlist)
    total = verificar_artifact_efectivo(
        artifact_root=artifact_root,
        mod_name="TexGen Output",
        mods_dir=mods_dir,
        data_root=data_root,
        enabled=enabled,
    )
    assert total == 1


def test_h1_c_canary_source(tmp_path: pathlib.Path) -> None:
    """TEST H1-C: para source_mod, sólo mods de mayor prioridad real y overwrite eclipsan.

    Un mod de menor prioridad con el mismo archivo NO invalida el canary.
    Un mod de mayor prioridad real SÍ invalida el canary.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    physical_data = tmp_path / "game" / "Data"
    physical_data.mkdir(parents=True)

    # High > TexGen Output > Low
    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+High\n+TexGen Output\n+Low\n", encoding="utf-8")

    texgen = mods_dir / "TexGen Output" / "textures"
    texgen.mkdir(parents=True)
    (texgen / "canary.dds").write_bytes(b"CANARY_BYTES")

    low = mods_dir / "Low" / "textures"
    low.mkdir(parents=True)
    (low / "canary.dds").write_bytes(b"CANARY_BYTES")

    high = mods_dir / "High" / "textures"
    high.mkdir(parents=True)

    # 1. Low contiene canary.dds pero es inferior: el canary de TexGen Output sigue siendo válido
    challenge = build_attestation_challenge_for_source(
        source_mod="TexGen Output",
        data_root=data_root,
        mods_dir=mods_dir,
        profile="Default",
        physical_data_dir=physical_data,
    )
    assert challenge.source_mod == "TexGen Output"
    assert challenge.relative_path.as_posix() == "textures/canary.dds"

    # 2. High contiene canary.dds y es superior: eclipsa el canary -> error
    (high / "canary.dds").write_bytes(b"OTHER_BYTES")
    with pytest.raises(VfsAttestationError, match="queda eclipsado"):
        build_attestation_challenge_for_source(
            source_mod="TexGen Output",
            data_root=data_root,
            mods_dir=mods_dir,
            profile="Default",
            physical_data_dir=physical_data,
        )


def test_h1_d_free_canary_with_overwrite(tmp_path: pathlib.Path) -> None:
    """TEST H1-D: selección libre de canary (source_mod=None) respeta precedencia de overwrite.

    Si overwrite contiene el archivo que un mod candidataría como canary,
    overwrite lo eclipsa y dicho archivo NO es elegible como canary.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    physical_data = tmp_path / "game" / "Data"
    physical_data.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+ModA\n+ModB\n", encoding="utf-8")

    # ModA tiene canary1.dds
    mod_a = mods_dir / "ModA" / "textures"
    mod_a.mkdir(parents=True)
    (mod_a / "canary1.dds").write_bytes(b"BYTES_A")

    # ModB tiene canary2.dds
    mod_b = mods_dir / "ModB" / "textures"
    mod_b.mkdir(parents=True)
    (mod_b / "canary2.dds").write_bytes(b"BYTES_B")

    # overwrite contiene canary1.dds (eclipsando ModA)
    overwrite = data_root / "overwrite" / "textures"
    overwrite.mkdir(parents=True)
    (overwrite / "canary1.dds").write_bytes(b"BYTES_OVERWRITE")

    # El canary libre NO puede elegir canary1.dds de ModA porque overwrite lo eclipsa;
    # debe elegir canary2.dds de ModB (que no está en overwrite).
    challenge = build_attestation_challenge(
        profile="Default",
        data_root=data_root,
        mods_dir=mods_dir,
        physical_data_dir=physical_data,
    )
    assert challenge.source_mod == "ModB"
    assert challenge.relative_path.as_posix() == "textures/canary2.dds"


def test_h1_e_false_green_adversarial(tmp_path: pathlib.Path) -> None:
    """TEST H1-E: demuestra la prevención del FALSO VERDE peligroso.

    En orden físico real de MO2:
    +HighPriorityMod
    +TexGen Output
    +LowPriorityMod

    HighPriorityMod pisa el artifact con bytes distintos.
    Con la semántica vieja (donde se creía que la última línea era mayor prioridad),
    HighPriorityMod se interpretaba erróneamente como prioridad inferior a TexGen Output,
    dejando pasar la corrida como verde cuando en runtime DynDOLOD consumiría los bytes
    ajenos de HighPriorityMod.

    Con la corrección H1: verifica que el gate de efectividad BLOQUEA (falla cerrado).
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text(
        "+HighPriorityMod\n+TexGen Output\n+LowPriorityMod\n",
        encoding="utf-8",
    )

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "lod.dds").write_bytes(b"AUTHORIZED_TEXGEN_BYTES")

    # HighPriorityMod tiene bytes distintos
    high_dir = mods_dir / "HighPriorityMod" / "textures"
    high_dir.mkdir(parents=True)
    (high_dir / "lod.dds").write_bytes(b"MALICIOUS_OVERRIDE_BYTES")

    # LowPriorityMod no pisa nada
    low_dir = mods_dir / "LowPriorityMod" / "meshes"
    low_dir.mkdir(parents=True)
    (low_dir / "unrelated.nif").write_bytes(b"UNRELATED")

    enabled = read_enabled_mods(modlist)
    with pytest.raises(ModEffectivityError, match="HighPriorityMod"):
        verificar_artifact_efectivo(
            artifact_root=artifact_root,
            mod_name="TexGen Output",
            mods_dir=mods_dir,
            data_root=data_root,
            enabled=enabled,
        )


def test_h1_f_false_red_adversarial(tmp_path: pathlib.Path) -> None:
    """TEST H1-F: demuestra la prevención del FALSO ROJO.

    En orden físico real de MO2:
    +TexGen Output
    +LowPriorityMod

    LowPriorityMod comparte el path con bytes distintos pero tiene prioridad real INFERIOR.
    Con la semántica vieja (donde se creía que la última línea ganaba), LowPriorityMod
    se consideraba superior y bloqueaba indebidamente la corrida (falso rojo).

    Con la corrección H1: TexGen Output gana el overlay y el gate pasa.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+TexGen Output\n+LowPriorityMod\n", encoding="utf-8")

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "lod.dds").write_bytes(b"AUTHORIZED_TEXGEN_BYTES")

    low_dir = mods_dir / "LowPriorityMod" / "textures"
    low_dir.mkdir(parents=True)
    (low_dir / "lod.dds").write_bytes(b"INFERIOR_OLD_TEXTURE_BYTES")

    enabled = read_enabled_mods(modlist)
    assert enabled == ("LowPriorityMod", "TexGen Output")
    total = verificar_artifact_efectivo(
        artifact_root=artifact_root,
        mod_name="TexGen Output",
        mods_dir=mods_dir,
        data_root=data_root,
        enabled=enabled,
    )
    assert total == 1


def test_h1_g_single_parser_anchor() -> None:
    """TEST H1-G: ancla estructural - modlist.txt se parsea por una sola primitive.

    read_enabled_mods() en sky_claw.local.mo2.vfs_attestation es la ÚNICA autoridad
    que determina la prioridad del modlist. Ningún otro módulo productivo puede
    abrir o parsear modlist.txt para computar prioridades por su cuenta.
    """
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    sky_claw_root = repo_root / "sky_claw"

    # Módulos productivos autorizados a realizar I/O sobre modlist.txt:
    # 1. vfs_attestation.py: read_enabled_mods (autoridad de prioridad) y hash crudo
    # 2. fomod/plugin_state.py: lectura de sets para condiciones booleanas fomod (sin orden ni prioridad)
    # 3. mo2/vfs.py: generador streaming de (mod, enabled) y escritor atómico
    modulos_con_io_autorizado = {
        "sky_claw/local/mo2/vfs_attestation.py",
        "sky_claw/local/fomod/plugin_state.py",
        "sky_claw/local/mo2/vfs.py",
    }

    # 1. Verificar que asset_scanner.py NO abre modlist.txt directamente, sino que delega en read_enabled_mods
    asset_scanner_source = (sky_claw_root / "local" / "assets" / "asset_scanner.py").read_text(encoding="utf-8")
    assert "read_enabled_mods(" in asset_scanner_source, "asset_scanner debe delegar en read_enabled_mods"
    assert "open(modlist_path" not in asset_scanner_source, "asset_scanner no debe abrir modlist.txt directamente"

    # 2. Censo exhaustivo de I/O en toda la base de código productiva:
    # Ningún módulo fuera de modulos_con_io_autorizado puede abrir modlist.txt para lectura
    culpables_io = []
    for py_file in sky_claw_root.rglob("*.py"):
        rel_posix = py_file.relative_to(repo_root).as_posix()
        tree = ast.parse(py_file.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            # Detectar llamadas a open(...), read_text(...), read_bytes(...) que reciban o involucren modlist.txt
            if isinstance(node, ast.Call):
                func_name = ""
                if isinstance(node.func, ast.Name):
                    func_name = node.func.id
                elif isinstance(node.func, ast.Attribute):
                    func_name = node.func.attr
                if func_name in {"open", "read_text", "read_bytes", "readlines"}:
                    # Verificar si en los argumentos o en el nodo hay referencia a modlist
                    code_segment = ast.unparse(node)
                    if "modlist" in code_segment and rel_posix not in modulos_con_io_autorizado:
                        culpables_io.append(f"{rel_posix}: {code_segment}")

    assert culpables_io == [], f"Se encontraron módulos no autorizados realizando I/O sobre modlist.txt: {culpables_io}"

    # 3. Verificar que la interpretación de prefijos de activación ('+', '-') para orden de prioridad
    # vive únicamente en read_enabled_mods y en vfs_attestation.py
    culpables_prioridad = []
    for py_file in sky_claw_root.rglob("*.py"):
        rel_posix = py_file.relative_to(repo_root).as_posix()
        content = py_file.read_text(encoding="utf-8")
        if ('startswith("+")' in content or "startswith('+')" in content) and rel_posix not in {
            "sky_claw/local/mo2/vfs_attestation.py",
            "sky_claw/local/mo2/vfs.py",
        }:
            culpables_prioridad.append(rel_posix)

    assert culpables_prioridad == [], (
        f"Se encontraron parsers de activación ('+') fuera de la primitiva central: {culpables_prioridad}"
    )


def test_asset_scanner_parse_modlist_usa_read_enabled_mods(tmp_path: pathlib.Path) -> None:
    """Verifica que AssetConflictDetector.parse_modlist devuelve mayor prioridad primero.

    Usa modlist.txt en orden real MO2:
    +ModAlto
    -ModDeshabilitado
    +ModBajo

    parse_modlist() debe devolver ['ModAlto', 'ModBajo'].
    """
    mo2 = tmp_path / "MO2"
    mods = mo2 / "mods"
    mods.mkdir(parents=True)
    profiles = mo2 / "profiles" / "Default"
    profiles.mkdir(parents=True)

    (profiles / "modlist.txt").write_text("+ModAlto\n-ModDeshabilitado\n+ModBajo\n", encoding="utf-8")

    detector = AssetConflictDetector(mods, profile_name="Default")
    resultado = detector.parse_modlist()
    assert resultado == ["ModAlto", "ModBajo"]
