"""H1 — Semántica de prioridad de modlist.txt de Mod Organizer 2.

Valida y congela la relación contractual entre el formato físico en disco de MO2
y la representación interna normalizada de Sky-Claw:

1. FORMATO FÍSICO EN DISCO (MO2):
   ``Profile::doWriteModlist`` recorre ``m_ModIndexByPriority`` en reversa
   (``crbegin()`` a ``crend()``), por lo que en disco:
   - Primera línea habilitada (``+Nombre``) = MAYOR prioridad entre mods regulares.
   - Última línea habilitada = MENOR prioridad entre mods regulares.
   - El overlay de ``overwrite`` permanece por encima de los mods regulares.

2. NORMALIZACIÓN CENTRAL EN EL BOUNDARY (read_enabled_mods):
   ``read_enabled_mods()`` invierte ese orden al leer (``tuple(reversed(enabled))``)
   para que la representación interna consumida por todo el resto de Sky-Claw sea
   estrictamente CRECIENTE:
   - Índice 0 = menor prioridad.
   - Último índice = mayor prioridad (convención "último gana").

3. CONSUMIDORES UNIFICADOS:
   - ``mod_effectivity.py`` (los superiores son ``enabled[indice + 1 :]``).
   - ``vfs_attestation.py`` (selección de canaries con overwrite y superiores).
   - ``asset_scanner.py`` (delega en ``read_enabled_mods``).
"""

from __future__ import annotations

import ast
import pathlib

import pytest

from sky_claw.app.security.path_validator import PathValidator
from sky_claw.local.assets.asset_scanner import AssetConflictDetector
from sky_claw.local.mo2.grass_profile import GrassProfileManager
from sky_claw.local.mo2.mod_effectivity import ModEffectivityError, verificar_artifact_efectivo
from sky_claw.local.mo2.vfs import MO2Controller
from sky_claw.local.mo2.vfs_attestation import (
    VfsAttestationError,
    build_attestation_challenge,
    build_attestation_challenge_for_source,
    read_enabled_mods,
)


def test_golden_real_mo2_modlist_format(tmp_path: pathlib.Path) -> None:
    """TEST GOLDEN: fixture realista con el formato exacto en disco que escribe MO2.

    En modlist.txt, la primera línea habilitada es la de mayor prioridad.
    read_enabled_mods() devuelve la tupla en orden de prioridad creciente
    (menor a mayor).
    """
    modlist = tmp_path / "modlist.txt"
    modlist.write_text(
        "# This file was automatically generated by Mod Organizer.\r\n"
        "+HighPriorityMod\r\n"
        "+TexGen Output\r\n"
        "+LowPriorityMod\r\n"
        "*separator_Textures\r\n"
        "-DisabledMod\r\n",
        encoding="utf-8-sig",
    )

    resultado = read_enabled_mods(modlist)
    assert resultado == ("LowPriorityMod", "TexGen Output", "HighPriorityMod")


def test_h1_a_effectivity(tmp_path: pathlib.Path) -> None:
    """TEST H1-A: efecto de la prioridad sobre el gate de efectividad del artifact.

    Escenario:
    High > TexGen Output > Low (en modlist.txt real: High primero, TexGen en medio, Low después).
    - Mismo path en Low con bytes diferentes: Low NO eclipsa TexGen Output.
    - Mismo path en High con bytes diferentes: High SÍ eclipsa TexGen Output -> BLOCK.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+High\n+TexGen Output\n+Low\n", encoding="utf-8")

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "test.dds").write_bytes(b"AUTHORIZED_TEXGEN")

    low_dir = mods_dir / "Low" / "textures"
    low_dir.mkdir(parents=True)
    (low_dir / "test.dds").write_bytes(b"LOW_BYTES_DIFFERENT")

    high_dir = mods_dir / "High" / "textures"
    high_dir.mkdir(parents=True)

    enabled = read_enabled_mods(modlist)
    assert enabled == ("Low", "TexGen Output", "High")

    # Paso 1: Low tiene bytes diferentes pero prioridad inferior: NO eclipsa
    total = verificar_artifact_efectivo(
        artifact_root=artifact_root,
        mod_name="TexGen Output",
        mods_dir=mods_dir,
        data_root=data_root,
        enabled=enabled,
    )
    assert total == 1

    # Paso 2: High tiene bytes diferentes y prioridad superior: SÍ eclipsa -> BLOCK
    (high_dir / "test.dds").write_bytes(b"HIGH_BYTES_DIFFERENT")
    with pytest.raises(ModEffectivityError, match="High"):
        verificar_artifact_efectivo(
            artifact_root=artifact_root,
            mod_name="TexGen Output",
            mods_dir=mods_dir,
            data_root=data_root,
            enabled=enabled,
        )


def test_h1_b_identical_higher_override(tmp_path: pathlib.Path) -> None:
    """TEST H1-B: mod de mayor prioridad con bytes idénticos NO bloquea efectividad.

    Preserva la propiedad de defense-in-depth: si un mod superior provee
    exactamente los mismos bytes del artifact, el contenido efectivo bajo USVFS
    sigue siendo el autorizado.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+High\n+TexGen Output\n+Low\n", encoding="utf-8")

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "diffuse.dds").write_bytes(b"EXACT_BYTES")

    high_dir = mods_dir / "High" / "textures"
    high_dir.mkdir(parents=True)
    (high_dir / "diffuse.dds").write_bytes(b"EXACT_BYTES")

    enabled = read_enabled_mods(modlist)
    total = verificar_artifact_efectivo(
        artifact_root=artifact_root,
        mod_name="TexGen Output",
        mods_dir=mods_dir,
        data_root=data_root,
        enabled=enabled,
    )
    assert total == 1


def test_h1_c_canary_source(tmp_path: pathlib.Path) -> None:
    """TEST H1-C: para source_mod, sólo mods de mayor prioridad real y overwrite eclipsan.

    Un mod de menor prioridad con el mismo archivo NO invalida el canary.
    Un mod de mayor prioridad real SÍ invalida el canary.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    physical_data = tmp_path / "game" / "Data"
    physical_data.mkdir(parents=True)

    # High > TexGen Output > Low
    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+High\n+TexGen Output\n+Low\n", encoding="utf-8")

    texgen = mods_dir / "TexGen Output" / "textures"
    texgen.mkdir(parents=True)
    (texgen / "canary.dds").write_bytes(b"CANARY_BYTES")

    low = mods_dir / "Low" / "textures"
    low.mkdir(parents=True)
    (low / "canary.dds").write_bytes(b"CANARY_BYTES")

    high = mods_dir / "High" / "textures"
    high.mkdir(parents=True)

    # 1. Low contiene canary.dds pero es inferior: el canary de TexGen Output sigue siendo válido
    challenge = build_attestation_challenge_for_source(
        source_mod="TexGen Output",
        data_root=data_root,
        mods_dir=mods_dir,
        profile="Default",
        physical_data_dir=physical_data,
    )
    assert challenge.source_mod == "TexGen Output"
    assert challenge.relative_path.as_posix() == "textures/canary.dds"

    # 2. High contiene canary.dds y es superior: eclipsa el canary -> error
    (high / "canary.dds").write_bytes(b"OTHER_BYTES")
    with pytest.raises(VfsAttestationError, match="queda eclipsado"):
        build_attestation_challenge_for_source(
            source_mod="TexGen Output",
            data_root=data_root,
            mods_dir=mods_dir,
            profile="Default",
            physical_data_dir=physical_data,
        )


def test_h1_d_free_canary_with_overwrite(tmp_path: pathlib.Path) -> None:
    """TEST H1-D: selección libre de canary (source_mod=None) respeta precedencia de overwrite.

    Si overwrite contiene el archivo que un mod candidataría como canary,
    overwrite lo eclipsa y dicho archivo NO es elegible como canary.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    physical_data = tmp_path / "game" / "Data"
    physical_data.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+ModA\n+ModB\n", encoding="utf-8")

    # ModA tiene canary1.dds
    mod_a = mods_dir / "ModA" / "textures"
    mod_a.mkdir(parents=True)
    (mod_a / "canary1.dds").write_bytes(b"BYTES_A")

    # ModB tiene canary2.dds
    mod_b = mods_dir / "ModB" / "textures"
    mod_b.mkdir(parents=True)
    (mod_b / "canary2.dds").write_bytes(b"BYTES_B")

    # overwrite contiene canary1.dds (eclipsando ModA)
    overwrite = data_root / "overwrite" / "textures"
    overwrite.mkdir(parents=True)
    (overwrite / "canary1.dds").write_bytes(b"BYTES_OVERWRITE")

    # El canary libre NO puede elegir canary1.dds de ModA porque overwrite lo eclipsa;
    # debe elegir canary2.dds de ModB (que no está en overwrite).
    challenge = build_attestation_challenge(
        profile="Default",
        data_root=data_root,
        mods_dir=mods_dir,
        physical_data_dir=physical_data,
    )
    assert challenge.source_mod == "ModB"
    assert challenge.relative_path.as_posix() == "textures/canary2.dds"


def test_h1_e_false_green_adversarial(tmp_path: pathlib.Path) -> None:
    """TEST H1-E: demuestra la prevención del FALSO VERDE peligroso.

    En orden físico real de MO2:
    +HighPriorityMod
    +TexGen Output
    +LowPriorityMod

    HighPriorityMod pisa el artifact con bytes distintos.
    Con la semántica vieja (donde se creía que la última línea era mayor prioridad),
    HighPriorityMod se interpretaba erróneamente como prioridad inferior a TexGen Output,
    dejando pasar la corrida como verde cuando en runtime DynDOLOD consumiría los bytes
    ajenos de HighPriorityMod.

    Con la corrección H1: verifica que el gate de efectividad BLOQUEA (falla cerrado).
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text(
        "+HighPriorityMod\n+TexGen Output\n+LowPriorityMod\n",
        encoding="utf-8",
    )

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "lod.dds").write_bytes(b"AUTHORIZED_TEXGEN_BYTES")

    # HighPriorityMod tiene bytes distintos
    high_dir = mods_dir / "HighPriorityMod" / "textures"
    high_dir.mkdir(parents=True)
    (high_dir / "lod.dds").write_bytes(b"MALICIOUS_OVERRIDE_BYTES")

    # LowPriorityMod no pisa nada
    low_dir = mods_dir / "LowPriorityMod" / "meshes"
    low_dir.mkdir(parents=True)
    (low_dir / "unrelated.nif").write_bytes(b"UNRELATED")

    enabled = read_enabled_mods(modlist)
    with pytest.raises(ModEffectivityError, match="HighPriorityMod"):
        verificar_artifact_efectivo(
            artifact_root=artifact_root,
            mod_name="TexGen Output",
            mods_dir=mods_dir,
            data_root=data_root,
            enabled=enabled,
        )


def test_h1_f_false_red_adversarial(tmp_path: pathlib.Path) -> None:
    """TEST H1-F: demuestra la prevención del FALSO ROJO.

    En orden físico real de MO2:
    +TexGen Output
    +LowPriorityMod

    LowPriorityMod comparte el path con bytes distintos pero tiene prioridad real INFERIOR.
    Con la semántica vieja (donde se creía que la última línea ganaba), LowPriorityMod
    se consideraba superior y bloqueaba indebidamente la corrida (falso rojo).

    Con la corrección H1: TexGen Output gana el overlay y el gate pasa.
    """
    data_root = tmp_path / "MO2"
    mods_dir = data_root / "mods"
    profile_dir = data_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+TexGen Output\n+LowPriorityMod\n", encoding="utf-8")

    artifact_root = mods_dir / "TexGen Output" / "textures"
    artifact_root.mkdir(parents=True)
    (artifact_root / "lod.dds").write_bytes(b"AUTHORIZED_TEXGEN_BYTES")

    low_dir = mods_dir / "LowPriorityMod" / "textures"
    low_dir.mkdir(parents=True)
    (low_dir / "lod.dds").write_bytes(b"INFERIOR_OLD_TEXTURE_BYTES")

    enabled = read_enabled_mods(modlist)
    assert enabled == ("LowPriorityMod", "TexGen Output")
    total = verificar_artifact_efectivo(
        artifact_root=artifact_root,
        mod_name="TexGen Output",
        mods_dir=mods_dir,
        data_root=data_root,
        enabled=enabled,
    )
    assert total == 1


# --- P1-C: Ancla Estructural de Familias y Censo Exhaustivo por AST ---

KNOWN_MODLIST_CENSUS: dict[str, set[str]] = {
    # Family A: Priority Readers (deben importar o definir read_enabled_mods)
    "FAMILY_A_PRIORITY_READERS": {
        "sky_claw/local/mo2/vfs_attestation.py",
        "sky_claw/local/assets/asset_scanner.py",
        "sky_claw/local/mo2/brokered_dyndolod.py",
    },
    # Family B: Writers (mutadores autorizados de modlist.txt)
    "FAMILY_B_WRITERS": {
        "sky_claw/local/mo2/vfs.py",
        "sky_claw/local/mo2/grass_profile.py",
        "sky_claw/app/agent/tools/system_tools.py",
    },
    # Family C: Non-Priority I/O (operaciones sobre modlist.txt sin interpretar jerarquía/orden)
    "FAMILY_C_NON_PRIORITY_IO": {
        "sky_claw/local/fomod/plugin_state.py",
        "sky_claw/local/mo2/vfs.py",
        "sky_claw/local/mo2/vfs_attestation.py",
        "sky_claw/local/mo2/profile_sandbox.py",
        "sky_claw/app/orchestrator/watcher_daemon.py",
        "sky_claw/local/discovery/scanner.py",
        "sky_claw/app/core/path_resolver.py",
    },
    # Family D: Documentación, payloads o referencias estáticas de nombre
    "FAMILY_D_DOC_OR_REFERENCE": {
        "sky_claw/app/core/event_payloads.py",
        "sky_claw/app/orchestrator/active_plugins.py",
        "sky_claw/app/orchestrator/asset_conflict_scan.py",
        "sky_claw/app/orchestrator/plugin_limit_guard.py",
        "sky_claw/app/orchestrator/sync_engine.py",
        "sky_claw/local/tools_installer.py",
        "sky_claw/local/local_config.py",
        "sky_claw/local/mo2/mod_effectivity.py",
        "sky_claw/local/validators/preflight.py",
        "sky_claw/local/validators/preflight_sensors.py",
        "sky_claw/local/validators/vfs_visibility.py",
        "sky_claw/local/validators/texgen_visibility.py",
        "sky_claw/local/tools/dyndolod_runner.py",
        "sky_claw/local/tools/dyndolod_service.py",
        "sky_claw/local/tools/loot_service.py",
        "sky_claw/local/tools/pandora_service.py",
        "sky_claw/local/tools/patcher_pipeline.py",
        "sky_claw/local/tools/synthesis_service.py",
        "sky_claw/local/tools/texgen_handoff.py",
        "sky_claw/local/tools/wrye_bash_service.py",
        "sky_claw/local/tools/xedit_service.py",
    },
}


def test_h1_g_structural_family_and_census_anchor() -> None:
    """TEST H1-G (rediseñado P1-C): ancla estructural de familias y censo exhaustivo por AST.

    Garantiza que:
    1. Todo consumidor de prioridad (Family A) importa o define la primitive canónica `read_enabled_mods`.
    2. Todo archivo en sky_claw/ que referencie `modlist.txt` está clasificado en una de las 4 familias.
    3. Si aparece un nuevo módulo productivo que interactúe con modlist.txt, el test falla exigiendo
       clasificación deliberada.
    """
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    sky_claw_root = repo_root / "sky_claw"

    all_registered = (
        KNOWN_MODLIST_CENSUS["FAMILY_A_PRIORITY_READERS"]
        | KNOWN_MODLIST_CENSUS["FAMILY_B_WRITERS"]
        | KNOWN_MODLIST_CENSUS["FAMILY_C_NON_PRIORITY_IO"]
        | KNOWN_MODLIST_CENSUS["FAMILY_D_DOC_OR_REFERENCE"]
    )

    # 1. Family A: Todo Priority Reader debe importar o definir read_enabled_mods
    for rel_posix in KNOWN_MODLIST_CENSUS["FAMILY_A_PRIORITY_READERS"]:
        file_path = repo_root / rel_posix
        tree = ast.parse(file_path.read_text(encoding="utf-8"))
        has_primitive = False
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "read_enabled_mods":
                has_primitive = True
                break
            if isinstance(node, ast.ImportFrom) and any(alias.name == "read_enabled_mods" for alias in node.names):
                has_primitive = True
                break
            if isinstance(node, ast.Name) and node.id == "read_enabled_mods":
                has_primitive = True
                break
        assert has_primitive, f"El consumidor de prioridad {rel_posix} no define ni importa read_enabled_mods()."

    # 2. Censo exhaustivo de todos los archivos productivos en sky_claw/
    unregistered_modules = []
    for py_file in sky_claw_root.rglob("*.py"):
        rel_posix = py_file.relative_to(repo_root).as_posix()
        tree = ast.parse(py_file.read_text(encoding="utf-8"))
        has_modlist_constant = False
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str) and "modlist.txt" in node.value:
                has_modlist_constant = True
                break
        if has_modlist_constant and rel_posix not in all_registered:
            unregistered_modules.append(rel_posix)

    assert unregistered_modules == [], (
        f"Se encontraron nuevos módulos productivos interactuando con modlist.txt que NO están "
        f"clasificados en KNOWN_MODLIST_CENSUS: {unregistered_modules}. "
        "Deben ser evaluados y clasificados deliberadamente en FAMILY_A (Priority Reader), "
        "FAMILY_B (Writer), FAMILY_C (Non-priority IO) o FAMILY_D (Doc/Ref)."
    )


def test_p1_c_mutant_unclassified_modlist_consumer_fails() -> None:
    """TEST MUTANTE P1-C: Comprueba que un módulo no clasificado hace fallar el censo."""
    simulated_new_module = "sky_claw/local/rogue_modlist_analyzer.py"
    all_registered = (
        KNOWN_MODLIST_CENSUS["FAMILY_A_PRIORITY_READERS"]
        | KNOWN_MODLIST_CENSUS["FAMILY_B_WRITERS"]
        | KNOWN_MODLIST_CENSUS["FAMILY_C_NON_PRIORITY_IO"]
        | KNOWN_MODLIST_CENSUS["FAMILY_D_DOC_OR_REFERENCE"]
    )
    assert simulated_new_module not in all_registered


# --- P1-A: Tests de inserción en máxima prioridad para writers (Grass Precache Config) ---


async def test_p1_a1_existing_conflict_grass_config_highest_priority(tmp_path: pathlib.Path) -> None:
    """TEST P1-A1: Grass config mod se inserta en máxima prioridad (primera posición en disco).

    Escenario con conflicto existente:
    +OtroModQueTieneGrassControl
    +OtroMod

    Al generar el grass config mod, en disco queda:
    +SkyClaw - Grass Precache Config
    +OtroModQueTieneGrassControl
    +OtroMod

    Y read_enabled_mods() produce internamente el config mod al final (mayor prioridad regular).
    Este caso no tiene overwrite; el overlay se valida por separado en grass_profile.
    """
    mo2_root = tmp_path / "MO2"
    profiles_dir = mo2_root / "profiles"
    source_profile = profiles_dir / "Default"
    clone_profile = profiles_dir / "SkyClaw-GrassCache"
    source_profile.mkdir(parents=True)
    clone_profile.mkdir(parents=True)

    # Configuración de modlist clonado con conflicto previo
    clon_modlist = clone_profile / "modlist.txt"
    clon_modlist.write_text("+OtroModQueTieneGrassControl\n+OtroMod\n", encoding="utf-8-sig")

    mods_dir = mo2_root / "mods"
    mods_dir.mkdir(parents=True)
    validator = PathValidator(roots=[mo2_root])
    manager = GrassProfileManager(mo2_root=mo2_root, path_validator=validator)

    mod_dir = await manager.build_config_mod(["Tamriel"])
    assert mod_dir.is_dir()

    # 1. En disco físico MO2: la primera entrada de mod es el config mod
    lineas = [ln.strip() for ln in clon_modlist.read_text(encoding="utf-8-sig").splitlines() if ln.strip()]
    assert lineas[0] == "+SkyClaw - Grass Precache Config"
    assert lineas == [
        "+SkyClaw - Grass Precache Config",
        "+OtroModQueTieneGrassControl",
        "+OtroMod",
    ]

    # 2. Internamente en Sky-Claw: read_enabled_mods() normaliza a orden creciente
    enabled = read_enabled_mods(clon_modlist)
    assert enabled == ("OtroMod", "OtroModQueTieneGrassControl", "SkyClaw - Grass Precache Config")
    assert enabled[-1] == "SkyClaw - Grass Precache Config"


async def test_p1_a2_idempotence_grass_config_highest_priority(tmp_path: pathlib.Path) -> None:
    """TEST P1-A2: Idempotencia - no duplicar si ya existe y reubicarlo si no está arriba."""
    mo2_root = tmp_path / "MO2"
    profile_dir = mo2_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    (mo2_root / "mods").mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    # Existe abajo con prioridad inferior
    modlist.write_text("+ModAlto\n+SkyClaw - Grass Precache Config\n+ModBajo\n", encoding="utf-8-sig")

    validator = PathValidator(roots=[mo2_root])
    ctrl = MO2Controller(mo2_root, validator)

    # Llamar add_mod_to_modlist con highest_priority=True dos veces
    await ctrl.add_mod_to_modlist("SkyClaw - Grass Precache Config", profile="Default", highest_priority=True)
    await ctrl.add_mod_to_modlist("SkyClaw - Grass Precache Config", profile="Default", highest_priority=True)

    lineas = [ln.strip() for ln in modlist.read_text(encoding="utf-8-sig").splitlines() if ln.strip()]
    # Debe aparecer exactamente una vez y en la primera posición
    assert lineas.count("+SkyClaw - Grass Precache Config") == 1
    assert lineas[0] == "+SkyClaw - Grass Precache Config"
    assert lineas == [
        "+SkyClaw - Grass Precache Config",
        "+ModAlto",
        "+ModBajo",
    ]


async def test_p1_a3_disabled_existing_entry_grass_config(tmp_path: pathlib.Path) -> None:
    """TEST P1-A3: Entrada deshabilitada existente se promueve a habilitada en máxima prioridad."""
    mo2_root = tmp_path / "MO2"
    profile_dir = mo2_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    (mo2_root / "mods").mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+ModAlto\n-SkyClaw - Grass Precache Config\n+ModBajo\n", encoding="utf-8-sig")

    validator = PathValidator(roots=[mo2_root])
    ctrl = MO2Controller(mo2_root, validator)

    await ctrl.add_mod_to_modlist_highest_priority("SkyClaw - Grass Precache Config", profile="Default")

    lineas = [ln.strip() for ln in modlist.read_text(encoding="utf-8-sig").splitlines() if ln.strip()]
    assert "-SkyClaw - Grass Precache Config" not in lineas
    assert lineas.count("+SkyClaw - Grass Precache Config") == 1
    assert lineas[0] == "+SkyClaw - Grass Precache Config"
    assert lineas == [
        "+SkyClaw - Grass Precache Config",
        "+ModAlto",
        "+ModBajo",
    ]


async def test_p1_a4_header_and_separator_preservation(tmp_path: pathlib.Path) -> None:
    """TEST P1-A4: Preserva encabezados MO2, líneas de comentarios y separadores."""
    mo2_root = tmp_path / "MO2"
    profile_dir = mo2_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    (mo2_root / "mods").mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "+HighMod\n"
        "-LowDisabled\n"
        "*separator_ui\n"
        "+LowestMod\n",
        encoding="utf-8-sig",
    )

    validator = PathValidator(roots=[mo2_root])
    ctrl = MO2Controller(mo2_root, validator)

    await ctrl.add_mod_to_modlist("NewConfigMod", profile="Default", highest_priority=True)

    lineas = [ln.strip() for ln in modlist.read_text(encoding="utf-8-sig").splitlines() if ln.strip()]
    # Encabezado intacto en la línea 0
    assert lineas[0] == "# This file was automatically generated by Mod Organizer."
    # Nuevo mod insertado inmediatamente después del encabezado
    assert lineas[1] == "+NewConfigMod"
    # Separador y resto de mods preservados intactos
    assert lineas[2:] == [
        "+HighMod",
        "-LowDisabled",
        "*separator_ui",
        "+LowestMod",
    ]


async def test_p1_a5_round_trip_writer_and_reader(tmp_path: pathlib.Path) -> None:
    """TEST P1-A5: Round-trip físico/canónico - el mod insertado con highest priority es enabled[-1]."""
    mo2_root = tmp_path / "MO2"
    profile_dir = mo2_root / "profiles" / "Default"
    profile_dir.mkdir(parents=True)
    (mo2_root / "mods").mkdir(parents=True)

    modlist = profile_dir / "modlist.txt"
    modlist.write_text("+Alpha\n+Beta\n+Gamma\n", encoding="utf-8-sig")

    validator = PathValidator(roots=[mo2_root])
    ctrl = MO2Controller(mo2_root, validator)

    await ctrl.add_mod_to_modlist_highest_priority("ZetaWinner", profile="Default")

    # read_enabled_mods canónico debe ponerlo último
    enabled = read_enabled_mods(modlist)
    assert enabled[-1] == "ZetaWinner"


# --- P1-B: Ancla de documentación canónica ---


def test_p1_b_canonical_agents_documentation_anchor() -> None:
    """TEST P1-B: Ancla de documentación - AGENTS.md y skyrim_sop.md no deben revertir a la semántica vieja.

    Verifica que:
    1. sky_claw/local/AGENTS.md define la regla canónica con read_enabled_mods como autoridad.
    2. Documenta el formato físico descendente de MO2 (primera entrada = mayor prioridad).
    3. Documenta la representación interna normalizada (read_enabled_mods orden creciente, enabled[-1] = mayor).
    4. No contiene la afirmación vieja errónea ("mod listed LAST has the highest" / "read bottom-up").
    """
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    agents_path = repo_root / "sky_claw" / "local" / "AGENTS.md"
    sop_path = repo_root / "docs" / "pipeline" / "skyrim_sop.md"

    agents_content = agents_path.read_text(encoding="utf-8")
    sop_content = sop_path.read_text(encoding="utf-8")

    # Claves canónicas requeridas en AGENTS.md
    assert "MO2 Physical Disk Format" in agents_content
    assert "read_enabled_mods()" in agents_content
    assert "vfs_attestation.py" in agents_content
    assert "descending priority" in agents_content or "prioridad descendente" in agents_content
    assert "highest regular-mod" in agents_content
    assert "overwrite` remains above regular mods" in agents_content
    assert "enabled[-1]" in agents_content

    # Prohibición de afirmaciones obsoletas del bug H1
    assert "the mod listed **LAST** has the **highest**" not in agents_content
    assert "the file is read bottom-up" not in agents_content

    # Skyrim SOP companion sync
    assert "read_enabled_mods" in sop_content
    assert "descendente" in sop_content


def test_asset_scanner_parse_modlist_usa_read_enabled_mods(tmp_path: pathlib.Path) -> None:
    """Verifica que AssetConflictDetector.parse_modlist devuelve mayor prioridad primero.

    Usa modlist.txt en orden real MO2:
    +ModAlto
    -ModDeshabilitado
    +ModBajo

    parse_modlist() debe devolver ['ModAlto', 'ModBajo'].
    """
    mo2 = tmp_path / "MO2"
    mods = mo2 / "mods"
    mods.mkdir(parents=True)
    profiles = mo2 / "profiles" / "Default"
    profiles.mkdir(parents=True)

    (profiles / "modlist.txt").write_text("+ModAlto\n-ModDeshabilitado\n+ModBajo\n", encoding="utf-8")

    detector = AssetConflictDetector(mods, profile_name="Default")
    resultado = detector.parse_modlist()
    assert resultado == ["ModAlto", "ModBajo"]
