"""Contrato semántico del fingerprint de perfil de la attestation VFS (#633).

El rig real de PR-586C (Windows, MO2 2.5.2 + USVFS) falló cerrado porque
`startApplication` reserializa `plugins.txt` entre el preview y el worker:
141 B → 96 B con la lista de plugins semánticamente intacta. Estos tests anclan
las dos mitades del contrato:

* **tolerado**: lo que MO2 puede reescribir sin cambiar el estado del perfil
  (BOM, header, EOL, líneas deshabilitadas, líneas de masters oficiales);
* **fail-closed**: todo cambio que sí cambia qué plugins carga el motor.

La evidencia de la semántica está en `CreationGamePlugins::readPluginList` /
`writePluginList` de MO2 (2.5.2 → master) y en el rig real referenciado en #633.
"""

from __future__ import annotations

import dataclasses
import hashlib
import pathlib

import pytest

from sky_claw.local.mo2.vfs_attestation import (
    VfsAttestationChallenge,
    VfsAttestationError,
    build_attestation_challenge,
    verify_vfs_attestation,
)

_MO2_HEADER = b"# This file was automatically generated by Mod Organizer.\r\n"
_UTF8_BOM = b"\xef\xbb\xbf"
_RIG_PROFILE = "SkyClaw-PR2-Rig"
_RIG_MASTERS = ("Skyrim.esm", "Update.esm", "Dawnguard.esm", "HearthFires.esm", "Dragonborn.esm")
_CANARY_RELATIVE = pathlib.PurePosixPath("SKSE/Plugins/skyclaw-canary.txt")
_CANARY_BYTES = b"canary-v1"
_ERROR_FINGERPRINT = "fingerprint del perfil cambió después del preview"


@dataclasses.dataclass(frozen=True, slots=True)
class _Perfil:
    """Fixture de perfil MO2 mínimo, con la vista virtual del canary ya montada."""

    mo2_root: pathlib.Path
    profile_dir: pathlib.Path
    game_root: pathlib.Path
    physical_data: pathlib.Path
    virtual_data: pathlib.Path
    profile: str

    def escribir_cc(self, nombres: tuple[str, ...]) -> None:
        """Declara contenido de Creation Club como lo hace el juego (`Skyrim.ccc`)."""
        if not nombres:
            return
        (self.game_root / "Skyrim.ccc").write_bytes(b"".join(nombre.encode("ascii") + b"\r\n" for nombre in nombres))

    def escribir_plugins(self, contenido: bytes) -> None:
        (self.profile_dir / "plugins.txt").write_bytes(contenido)

    def challenge(self) -> VfsAttestationChallenge:
        return build_attestation_challenge(
            mo2_root=self.mo2_root,
            profile=self.profile,
            physical_data_dir=self.physical_data,
        )

    def verificar(self, challenge: VfsAttestationChallenge) -> None:
        verify_vfs_attestation(
            challenge=challenge,
            mo2_root=self.mo2_root,
            profile=self.profile,
            virtual_data_dir=self.virtual_data,
        )


def _crear_perfil(
    tmp_path: pathlib.Path,
    *,
    plugins: bytes | None = None,
    profile: str = _RIG_PROFILE,
    modlist: str = "+CanaryMod\n-OtherMod\n",
    canary_relativo: pathlib.PurePosixPath = _CANARY_RELATIVE,
    canary_bytes: bytes = _CANARY_BYTES,
    cc: tuple[str, ...] = (),
) -> _Perfil:
    """Perfil MO2 mínimo con los dos `Data` colgando del MISMO game root.

    En producción el preview lee el `Data` físico y el worker lee el mismo
    `<juego>/Data` a través de USVFS, así que ambos derivan de ahí el mismo
    `primaryPlugins()` (masters + `Skyrim.ccc`). Acá son directorios distintos
    sólo para poder modelar que el canary NO existe en el `Data` físico.
    """
    mo2_root = tmp_path / "MO2"
    profile_dir = mo2_root / "profiles" / profile
    game_root = tmp_path / "Skyrim"
    physical_data = game_root / "Data"
    for directorio in (profile_dir, physical_data):
        directorio.mkdir(parents=True, exist_ok=True)
    (profile_dir / "modlist.txt").write_text(modlist, encoding="utf-8-sig")
    for mod_name in ("CanaryMod", "OtherMod", "ZebraMod"):
        canary = mo2_root / "mods" / mod_name / pathlib.Path(*canary_relativo.parts)
        canary.parent.mkdir(parents=True, exist_ok=True)
        canary.write_bytes(canary_bytes)
    perfil = _Perfil(
        mo2_root=mo2_root,
        profile_dir=profile_dir,
        game_root=game_root,
        physical_data=physical_data,
        virtual_data=game_root / "Data-en-vivo",
        profile=profile,
    )
    visible = perfil.virtual_data / pathlib.Path(*canary_relativo.parts)
    visible.parent.mkdir(parents=True, exist_ok=True)
    visible.write_bytes(canary_bytes)
    if plugins is not None:
        perfil.escribir_plugins(plugins)
    perfil.escribir_cc(cc)
    return perfil


# ---------------------------------------------------------------------------
# Regresión del rig real (R3 de PR-586C)
# ---------------------------------------------------------------------------


def _plugins_rig_antes() -> bytes:
    """Forma pre-lanzamiento: BOM + header + masters oficiales con estrella.

    Reproduce el tamaño observado (141 B): 3 (BOM) + 59 (header CRLF) + 77
    (cinco líneas ``*master``) + 2 (línea vacía final).
    """
    masters = b"".join(b"*" + name.encode("ascii") + b"\r\n" for name in _RIG_MASTERS)
    return _UTF8_BOM + _MO2_HEADER + masters + b"\r\n"


def _plugins_rig_despues() -> bytes:
    """Forma que escribe MO2 al lanzar: header + plugins no oficiales sin estrella.

    Reproduce el tamaño observado (96 B): 59 (header) + 18 + 19 (dos entradas
    deshabilitadas de 16 y 17 caracteres).
    """
    return _MO2_HEADER + b"RigCanaryMod.esp\r\n" + b"SkyClawCanary.esp\r\n"


def test_regresion_rig_real_reproduce_las_formas_observadas() -> None:
    """Ancla de fidelidad: las formas sintéticas miden 141 B y 96 B como el rig."""
    assert len(_plugins_rig_antes()) == 141
    assert len(_plugins_rig_despues()) == 96


def test_regresion_rig_real_la_reserializacion_de_mo2_no_cambia_el_fingerprint(tmp_path: pathlib.Path) -> None:
    """MO2 reescribe plugins.txt entre preview y worker: la attestation sigue OK."""
    perfil = _crear_perfil(tmp_path, plugins=_plugins_rig_antes())

    challenge = perfil.challenge()
    perfil.escribir_plugins(_plugins_rig_despues())
    perfil.verificar(challenge)

    assert challenge.profile_fingerprint == perfil.challenge().profile_fingerprint


def test_regresion_rig_real_un_vecino_semantico_sigue_fallando(tmp_path: pathlib.Path) -> None:
    """La misma forma que MO2 escribe, con un plugin más, NO es una reserialización."""
    perfil = _crear_perfil(tmp_path, plugins=_plugins_rig_antes())

    challenge = perfil.challenge()
    perfil.escribir_plugins(_plugins_rig_despues() + b"*RigExtra.esp\r\n")
    assert perfil.challenge().profile_fingerprint != challenge.profile_fingerprint
    with pytest.raises(VfsAttestationError, match=_ERROR_FINGERPRINT):
        perfil.verificar(challenge)


def test_regresion_rig_real_el_canary_y_el_resto_del_perfil_cambian_el_digest(tmp_path: pathlib.Path) -> None:
    """La tolerancia es solo de representación: los bytes crudos siguen contando."""
    perfil = _crear_perfil(tmp_path, plugins=_plugins_rig_antes())
    original = perfil.challenge().profile_fingerprint

    (perfil.profile_dir / "loadorder.txt").write_bytes(_MO2_HEADER + b"Skyrim.esm\r\n")
    con_loadorder = perfil.challenge().profile_fingerprint

    assert con_loadorder != original


# ---------------------------------------------------------------------------
# Equivalencias toleradas (reserialización de MO2)
# ---------------------------------------------------------------------------

_PLUGINS_BASE = _MO2_HEADER + b"*RigCanaryMod.esp\r\n" + b"RigDisabled.esp\r\n"


@pytest.mark.parametrize(
    ("descripcion", "contenido"),
    [
        pytest.param("bom", _UTF8_BOM + _PLUGINS_BASE, id="bom-agregado"),
        pytest.param("lf", _PLUGINS_BASE.replace(b"\r\n", b"\n"), id="lf-en-vez-de-crlf"),
        pytest.param("cr", _PLUGINS_BASE.replace(b"\r\n", b"\r"), id="cr-suelto"),
        pytest.param("sin-header", _PLUGINS_BASE.split(b"\r\n", 1)[1], id="header-ausente"),
        pytest.param(
            "header-propio",
            b"# Managed by LOOT\r\n" + _PLUGINS_BASE.split(b"\r\n", 1)[1],
            id="header-distinto",
        ),
        pytest.param(
            "espacios",
            _MO2_HEADER + b"  *RigCanaryMod.esp  \r\n\tRigDisabled.esp\t\r\n\r\n",
            id="espacios-y-lineas-vacias",
        ),
        pytest.param(
            "deshabilitado-agregado",
            _PLUGINS_BASE + b"OtroDeshabilitado.esp\r\n",
            id="linea-deshabilitada-agregada",
        ),
        pytest.param(
            "deshabilitado-quitado",
            _PLUGINS_BASE.replace(b"RigDisabled.esp\r\n", b""),
            id="linea-deshabilitada-quitada",
        ),
        pytest.param(
            "deshabilitado-reordenado",
            _MO2_HEADER + b"RigDisabled.esp\r\n*RigCanaryMod.esp\r\n",
            id="deshabilitado-reordenado-antes-del-habilitado",
        ),
        pytest.param(
            "masters-oficiales",
            _MO2_HEADER + _plugins_rig_antes().split(_MO2_HEADER, 1)[1] + _PLUGINS_BASE.split(b"\r\n", 1)[1],
            id="masters-oficiales-listados-y-con-estrella",
        ),
        pytest.param(
            "masters-sin-estrella",
            _MO2_HEADER + b"Skyrim.esm\r\nUpdate.esm\r\n" + _PLUGINS_BASE.split(b"\r\n", 1)[1],
            id="masters-oficiales-sin-estrella",
        ),
    ],
)
def test_representaciones_equivalentes_comparten_fingerprint(
    tmp_path: pathlib.Path,
    descripcion: str,  # noqa: ARG001 — id legible en el reporte de pytest
    contenido: bytes,
) -> None:
    """Toda reserialización demostrada como neutra conserva el fingerprint."""
    perfil = _crear_perfil(tmp_path, plugins=_PLUGINS_BASE)
    base = perfil.challenge()

    perfil.escribir_plugins(contenido)
    perfil.verificar(base)

    assert base.profile_fingerprint == perfil.challenge().profile_fingerprint


def test_plugins_txt_ausente_vacio_o_solo_header_son_el_mismo_estado(tmp_path: pathlib.Path) -> None:
    """Sin plugins no oficiales habilitados el estado es el mismo, exista o no el archivo."""
    solo_header = _crear_perfil(tmp_path / "a", plugins=_MO2_HEADER)
    vacio = _crear_perfil(tmp_path / "b", plugins=b"")
    ausente = _crear_perfil(tmp_path / "c")

    assert solo_header.challenge().profile_fingerprint == vacio.challenge().profile_fingerprint
    assert solo_header.challenge().profile_fingerprint == ausente.challenge().profile_fingerprint


def test_el_orden_de_los_plugins_habilitados_es_semantico(tmp_path: pathlib.Path) -> None:
    """Reordenar líneas habilitadas cambia el estado (es el orden del perfil)."""
    primero = _crear_perfil(
        tmp_path / "a",
        plugins=_MO2_HEADER + b"*A.esp\r\n*B.esp\r\n",
    )
    segundo = _crear_perfil(
        tmp_path / "b",
        plugins=_MO2_HEADER + b"*B.esp\r\n*A.esp\r\n",
    )

    assert primero.challenge().profile_fingerprint != segundo.challenge().profile_fingerprint


# ---------------------------------------------------------------------------
# Mutaciones semánticas: deben fallar cerrado
# ---------------------------------------------------------------------------

_MUTACIONES = [
    pytest.param("plugin-agregado", _PLUGINS_BASE + b"*RigExtra.esp\r\n", id="plugin-habilitado-agregado"),
    pytest.param(
        "plugin-quitado",
        _MO2_HEADER + b"RigDisabled.esp\r\n",
        id="plugin-habilitado-quitado",
    ),
    pytest.param(
        "plugin-cambiado",
        _MO2_HEADER + b"*OtroCanary.esp\r\nRigDisabled.esp\r\n",
        id="plugin-habilitado-renombrado",
    ),
    pytest.param(
        "deshabilitado",
        _MO2_HEADER + b"RigCanaryMod.esp\r\nRigDisabled.esp\r\n",
        id="habilitado-pasa-a-deshabilitado",
    ),
    pytest.param(
        "habilitado",
        _MO2_HEADER + b"*RigCanaryMod.esp\r\n*RigDisabled.esp\r\n",
        id="deshabilitado-pasa-a-habilitado",
    ),
    pytest.param("case", _MO2_HEADER + b"*rigcanarymod.esp\r\nRigDisabled.esp\r\n", id="case-del-habilitado-cambia"),
    pytest.param(
        "orden",
        _MO2_HEADER + b"*B.esp\r\n*RigCanaryMod.esp\r\n",
        id="orden-de-habilitados-cambia",
    ),
    pytest.param(
        "master-oficial-en-lugar-del-plugin",
        _MO2_HEADER + b"*Dawnguard.esm\r\nRigDisabled.esp\r\n",
        id="habilitado-reemplazado-por-master-oficial",
    ),
]


@pytest.mark.parametrize(("descripcion", "contenido"), _MUTACIONES)
def test_mutacion_semantica_cambia_el_fingerprint_y_falla_cerrado(
    tmp_path: pathlib.Path,
    descripcion: str,  # noqa: ARG001 — id legible en el reporte de pytest
    contenido: bytes,
) -> None:
    """Cambiar el estado real del perfil no se puede confundir con una reserialización."""
    perfil = _crear_perfil(tmp_path, plugins=_PLUGINS_BASE)
    base = perfil.challenge()

    perfil.escribir_plugins(contenido)
    assert perfil.challenge().profile_fingerprint != base.profile_fingerprint
    with pytest.raises(VfsAttestationError, match=_ERROR_FINGERPRINT):
        perfil.verificar(base)


@pytest.mark.parametrize(
    ("descripcion", "contenido_mutado"),
    [
        pytest.param("mod", "+CanaryMod\n", id="mod-deshabilitado-en-modlist"),
        pytest.param("modlist", "-RigCanaryMod\n", id="modlist-cambia-de-mod"),
        pytest.param("prioridad", "+ZebraMod\n+CanaryMod\n", id="prioridad-de-mods-cambiada"),
    ],
)
def test_drift_de_modlist_sigue_fallando_cerrado(
    tmp_path: pathlib.Path,
    descripcion: str,  # noqa: ARG001 — id legible en el reporte de pytest
    contenido_mutado: str,
) -> None:
    """`modlist.txt` se hashea en crudo: cualquier byte distinto cambia el fingerprint."""
    perfil = _crear_perfil(tmp_path, plugins=_PLUGINS_BASE)
    base = perfil.challenge()

    (perfil.profile_dir / "modlist.txt").write_text(contenido_mutado, encoding="utf-8-sig")
    with pytest.raises(VfsAttestationError):
        perfil.verificar(base)


# ---------------------------------------------------------------------------
# Entrada malformada: falla cerrado, nunca "best effort"
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("descripcion", "contenido"),
    [
        pytest.param("utf16", "# h\r\n*RigCanaryMod.esp\r\n".encode("utf-16-le"), id="codificacion-utf16"),
        pytest.param("sin-extension", _MO2_HEADER + b"*LEEME.txt\r\n", id="nombre-sin-extension-de-plugin"),
        pytest.param("sin-nombre", _MO2_HEADER + b"*\r\n", id="estrella-sin-nombre"),
        pytest.param("sin-nombre-solo-espacios", _MO2_HEADER + b"*   \r\n", id="estrella-solo-espacios"),
        pytest.param("estrella-interior", _MO2_HEADER + b"*Ri*gCanary.esp\r\n", id="estrella-interior"),
        pytest.param("traversal", _MO2_HEADER + b"*../evil.esp\r\n", id="traversal"),
        pytest.param("separador", _MO2_HEADER + b"*Mod\\evil.esp\r\n", id="separador-de-ruta"),
        pytest.param("control", _MO2_HEADER + b"*Rig\x01Canary.esp\r\n", id="caracter-de-control"),
        pytest.param("nul", _MO2_HEADER + b"*Rig\x00Canary.esp\r\n", id="nul-interior"),
        pytest.param("duplicado", _MO2_HEADER + b"*RigCanaryMod.esp\r\n*RigCanaryMod.esp\r\n", id="duplicado"),
        pytest.param(
            "duplicado-case",
            _MO2_HEADER + b"*RigCanaryMod.esp\r\n*rigcanarymod.esp\r\n",
            id="duplicado-case-insensitive",
        ),
    ],
)
def test_plugins_txt_malformado_falla_cerrado(
    tmp_path: pathlib.Path,
    descripcion: str,  # noqa: ARG001 — id legible en el reporte de pytest
    contenido: bytes,
) -> None:
    """Un archivo que no se puede interpretar NO produce un fingerprint válido."""
    perfil = _crear_perfil(tmp_path, plugins=_PLUGINS_BASE)
    base = perfil.challenge()

    perfil.escribir_plugins(contenido)
    with pytest.raises(VfsAttestationError, match="plugins.txt"):
        perfil.challenge()
    with pytest.raises(VfsAttestationError, match="plugins.txt"):
        perfil.verificar(base)


# ---------------------------------------------------------------------------
# Nombres reales de plugin: la codepage del sistema, no ASCII
# ---------------------------------------------------------------------------

#: `plugins.txt` se escribe con encoding ``System`` (página de código), así que
#: un nombre con acentos llega como un byte > 0x7E legítimo — no como un error.
_ESPADA_CP1252 = "EspadaÉlfica.esp".encode("cp1252")
_ARMERIA_CP1252 = "ArmeríaDwemer.esl".encode("cp1252")


def test_nombres_no_ascii_son_validos_y_semanticos(tmp_path: pathlib.Path) -> None:
    """Un nombre de la codepage del sistema no puede volverse un fail-closed falso."""
    perfil = _crear_perfil(tmp_path, plugins=_MO2_HEADER + b"*" + _ESPADA_CP1252 + b"\r\n")
    base = perfil.challenge()

    perfil.escribir_plugins(_MO2_HEADER + b"*" + _ARMERIA_CP1252 + b"\r\n")
    assert perfil.challenge().profile_fingerprint != base.profile_fingerprint
    with pytest.raises(VfsAttestationError, match=_ERROR_FINGERPRINT):
        perfil.verificar(base)


def test_nombres_no_ascii_en_utf8_tambien_son_aceptados(tmp_path: pathlib.Path) -> None:
    """El contrato es de bytes: otra codificación del mismo nombre es otro byte, no un error."""
    perfil = _crear_perfil(tmp_path, plugins=_MO2_HEADER + b"*" + "EspadaÉlfica.esp".encode() + b"\r\n")

    assert perfil.challenge().profile_fingerprint


def test_espacios_interiores_son_validos(tmp_path: pathlib.Path) -> None:
    """`Unofficial Skyrim Special Edition Patch.esp` es un nombre real y frecuente."""
    ussep = b"*Unofficial Skyrim Special Edition Patch.esp\r\n"
    perfil = _crear_perfil(tmp_path, plugins=_MO2_HEADER + ussep + b"*RigCanaryMod.esp\r\n")
    base = perfil.challenge()

    perfil.escribir_plugins(_MO2_HEADER + ussep)
    assert perfil.challenge().profile_fingerprint != base.profile_fingerprint


def test_duplicado_no_ascii_case_insensitive_falla_cerrado(tmp_path: pathlib.Path) -> None:
    """Para Windows `EspadaÉlfica.esp` y `espadaélfica.esp` son el mismo archivo."""
    perfil = _crear_perfil(tmp_path, plugins=_PLUGINS_BASE)
    perfil.escribir_plugins(
        _MO2_HEADER + b"*" + _ESPADA_CP1252 + b"\r\n*" + "espadaélfica.esp".encode("cp1252") + b"\r\n"
    )

    with pytest.raises(VfsAttestationError, match="repite"):
        perfil.challenge()


def test_no_colapsa_pares_que_windows_no_considera_iguales(tmp_path: pathlib.Path) -> None:
    """`Straße.esp` y `Strasse.esp` son archivos distintos: no se fabrica un duplicado."""
    perfil = _crear_perfil(
        tmp_path,
        plugins=_MO2_HEADER + b"*Stra\xdfe.esp\r\n*Strasse.esp\r\n",
    )

    assert perfil.challenge().profile_fingerprint


# ---------------------------------------------------------------------------
# Creation Club: el resto de `primaryPlugins()`
# ---------------------------------------------------------------------------

_CC_FISH = "ccBGSSSE001-Fish.esl"


def test_mo2_que_borra_la_linea_de_creation_club_no_cambia_el_fingerprint(tmp_path: pathlib.Path) -> None:
    """MO2 también omite del `plugins.txt` el contenido de Creation Club.

    `GameSkyrimSE::primaryPlugins()` = masters base + `CCPlugins()` (leído de
    `Skyrim.ccc`), y `CreationGamePlugins::writePluginList` no escribe ninguna
    línea de ese conjunto, así que la reserialización las borra sin cambiar qué
    carga el motor.
    """
    perfil = _crear_perfil(
        tmp_path,
        plugins=_MO2_HEADER + b"*" + _CC_FISH.encode("ascii") + b"\r\n*RigCanaryMod.esp\r\n",
        cc=(_CC_FISH,),
    )
    challenge = perfil.challenge()

    perfil.escribir_plugins(_MO2_HEADER + b"*RigCanaryMod.esp\r\n")
    perfil.verificar(challenge)

    assert challenge.profile_fingerprint == perfil.challenge().profile_fingerprint


def test_creation_club_no_declarado_por_el_juego_sigue_siendo_estado(tmp_path: pathlib.Path) -> None:
    """Un `cc*` que `Skyrim.ccc` no declara es un mod más: no se asume por prefijo."""
    con_linea = _crear_perfil(
        tmp_path / "a",
        plugins=_MO2_HEADER + b"*ccMiModPropio.esl\r\n",
        cc=(_CC_FISH,),
    )
    sin_linea = _crear_perfil(tmp_path / "b", plugins=_MO2_HEADER, cc=(_CC_FISH,))

    assert con_linea.challenge().profile_fingerprint != sin_linea.challenge().profile_fingerprint


def test_skyrim_ccc_cambia_la_interpretacion_de_la_linea(tmp_path: pathlib.Path) -> None:
    """Declarar ese CC cambia el conjunto primario: la misma línea deja de ser estado."""
    declarado = _crear_perfil(
        tmp_path / "a",
        plugins=_MO2_HEADER + b"*" + _CC_FISH.encode("ascii") + b"\r\n",
        cc=(_CC_FISH,),
    )
    no_declarado = _crear_perfil(
        tmp_path / "b",
        plugins=_MO2_HEADER + b"*" + _CC_FISH.encode("ascii") + b"\r\n",
    )

    assert declarado.challenge().profile_fingerprint != no_declarado.challenge().profile_fingerprint


def test_skyrim_ccc_ausente_o_vacio_es_el_mismo_conjunto(tmp_path: pathlib.Path) -> None:
    """Sin archivo (o vacío) el juego no declara CC: mismo conjunto primario."""
    ausente = _crear_perfil(tmp_path / "a", plugins=_PLUGINS_BASE)
    vacio = _crear_perfil(tmp_path / "b", plugins=_PLUGINS_BASE)
    (vacio.game_root / "Skyrim.ccc").write_bytes(b"")

    assert ausente.challenge().profile_fingerprint == vacio.challenge().profile_fingerprint


# ---------------------------------------------------------------------------
# Bindings que NO se relajan
# ---------------------------------------------------------------------------


def test_binding_de_source_mod(tmp_path: pathlib.Path) -> None:
    """El mismo archivo canario en otro mod cambia el fingerprint."""
    canary = _crear_perfil(tmp_path / "a", plugins=_PLUGINS_BASE, modlist="+CanaryMod\n")
    zebra = _crear_perfil(tmp_path / "b", plugins=_PLUGINS_BASE, modlist="+ZebraMod\n")

    assert canary.challenge().source_mod == "CanaryMod"
    assert zebra.challenge().source_mod == "ZebraMod"
    assert canary.challenge().profile_fingerprint != zebra.challenge().profile_fingerprint


def test_binding_de_source_mod_con_el_mismo_archivo_y_los_mismos_bytes(tmp_path: pathlib.Path) -> None:
    """Dos mods con el mismo archivo canario: solo el mod de origen distingue el estado.

    `modlist.txt` crudo y el SHA del canario son idénticos en ambos intentos; el
    único cambio es cuál mod aporta el archivo (borrar la copia de mayor
    prioridad degrada el canary a la copia siguiente). Si el digest no atara
    `source_mod`, un challenge emitido para un mod reutilizaría el fingerprint
    de otro.
    """
    perfil = _crear_perfil(tmp_path, plugins=_PLUGINS_BASE, modlist="+CanaryMod\n+ZebraMod\n")
    original = perfil.challenge()
    assert original.source_mod == "ZebraMod"

    (perfil.mo2_root / "mods" / "ZebraMod" / pathlib.Path(*_CANARY_RELATIVE.parts)).unlink()
    degradado = perfil.challenge()

    assert degradado.source_mod == "CanaryMod"
    assert degradado.sha256 == original.sha256
    assert degradado.profile_fingerprint != original.profile_fingerprint


def test_binding_de_relative_path(tmp_path: pathlib.Path) -> None:
    """Otro archivo del mismo mod (mismo SHA) cambia el fingerprint."""
    primero = _crear_perfil(tmp_path / "a", plugins=_PLUGINS_BASE)
    segundo = _crear_perfil(
        tmp_path / "b",
        plugins=_PLUGINS_BASE,
        canary_relativo=pathlib.PurePosixPath("SKSE/Plugins/otro-canary.txt"),
    )

    assert primero.challenge().sha256 == segundo.challenge().sha256
    assert primero.challenge().relative_path != segundo.challenge().relative_path
    assert primero.challenge().profile_fingerprint != segundo.challenge().profile_fingerprint


def test_binding_de_canary_sha(tmp_path: pathlib.Path) -> None:
    """El mismo path con otro contenido cambia el fingerprint."""
    original = _crear_perfil(tmp_path / "a", plugins=_PLUGINS_BASE)
    distinto = _crear_perfil(tmp_path / "b", plugins=_PLUGINS_BASE, canary_bytes=b"canary-v2")

    assert original.challenge().relative_path == distinto.challenge().relative_path
    assert original.challenge().sha256 != distinto.challenge().sha256
    assert original.challenge().profile_fingerprint != distinto.challenge().profile_fingerprint


def test_binding_de_perfil(tmp_path: pathlib.Path) -> None:
    """El perfil forma parte del digest: Default vs rig no comparten fingerprint."""
    default = _crear_perfil(tmp_path / "a", plugins=_PLUGINS_BASE, profile="Default")
    rig = _crear_perfil(tmp_path / "b", plugins=_PLUGINS_BASE, profile=_RIG_PROFILE)

    assert default.challenge().profile_fingerprint != rig.challenge().profile_fingerprint


# ---------------------------------------------------------------------------
# Anclas de construcción del digest
# ---------------------------------------------------------------------------


def test_dominio_v2_no_reutiliza_v1(tmp_path: pathlib.Path) -> None:
    """El digest v2 no puede confundirse con el v1 (misma tupla, otra semántica)."""
    perfil = _crear_perfil(tmp_path, plugins=_plugins_rig_antes())
    challenge = perfil.challenge()

    assert challenge.profile_fingerprint != _digest_v1(perfil, challenge)


def test_conjunto_siempre_activo_anclado(tmp_path: pathlib.Path) -> None:
    """`primaryPlugins()` = masters oficiales (Sky-Claw) + CC declarado por el juego."""
    from sky_claw.local.mo2 import plugin_sources, vfs_attestation

    esperado = frozenset(name.lower() for name in _RIG_MASTERS)
    assert esperado == vfs_attestation._ALWAYS_ACTIVE_PLUGINS
    assert frozenset(name.lower() for name in plugin_sources.OFFICIAL_MASTERS) == esperado

    data = tmp_path / "Skyrim" / "Data"
    data.mkdir(parents=True)
    assert vfs_attestation._always_active_plugins(data) == esperado

    (data.parent / "Skyrim.ccc").write_bytes(
        b"ccBGSSSE001-Fish.esl\r\nCCQDRSSE001-SurvivalMode.esl\r\nccBGSSSE001-Fish.esl\r\n"
    )
    assert vfs_attestation._always_active_plugins(data) == esperado | {
        "ccbgssse001-fish.esl",
        "ccqdrssE001-SurvivalMode.esl".lower(),
    }


def test_framing_del_digest_evita_colision_por_reparto_de_bytes(tmp_path: pathlib.Path) -> None:
    """Dos estados distintos no pueden producir el mismo digest por reencuadre.

    Con la concatenación sin largo de v1, `modlist.txt` vacío + `loadorder.txt`
    con el literal ``\\0file\\0loadorder.txt`` producía exactamente el mismo
    material que el reparto inverso (colisión verificada sobre el esquema v1).
    El framing length-prefixed lo cierra.
    """
    imitacion = b"\x00file\x00settings.ini"

    vacio = _crear_perfil(tmp_path / "a", plugins=_PLUGINS_BASE)
    (vacio.profile_dir / "loadorder.txt").write_bytes(b"")
    (vacio.profile_dir / "settings.ini").write_bytes(imitacion)
    imitado = _crear_perfil(tmp_path / "b", plugins=_PLUGINS_BASE)
    (imitado.profile_dir / "loadorder.txt").write_bytes(imitacion)
    (imitado.profile_dir / "settings.ini").write_bytes(b"")

    # El esquema v1 (previo a #633) colisionaba: mismo material de digest.
    assert _digest_v1(vacio, vacio.challenge()) == _digest_v1(imitado, imitado.challenge())
    # El esquema v2 los distingue.
    assert vacio.challenge().profile_fingerprint != imitado.challenge().profile_fingerprint


def _digest_v1(perfil: _Perfil, challenge: VfsAttestationChallenge) -> str:
    """Reimplementación local del digest v1 (crudo) para anclar el bump de dominio."""
    digest = hashlib.sha256()
    digest.update(b"skyclaw-vfs-profile-v1\0")
    digest.update(perfil.profile.encode("utf-8"))
    for filename in ("modlist.txt", "plugins.txt", "loadorder.txt", "settings.ini", "settings.txt"):
        path = perfil.profile_dir / filename
        digest.update(b"\0file\0")
        digest.update(filename.encode("ascii"))
        try:
            digest.update(path.read_bytes())
        except FileNotFoundError:
            digest.update(b"\0missing\0")
    digest.update(b"\0canary\0")
    digest.update(challenge.source_mod.encode("utf-8"))
    digest.update(challenge.relative_path.as_posix().encode("utf-8"))
    digest.update(challenge.sha256.encode("ascii"))
    return digest.hexdigest()
