"""Runtime Vault (RV-1): identidad de runtime + verificación de árboles.

Core autocontenido y sin dependencias de #493: la identidad de runtime llega
como datos de entrada (nunca se escanea el host) y la identidad de un árbol es
(digest, files, bytes) derivada de (relpath, size, sha256) por archivo, sin
mtime y sin root físico. La única dependencia fuera de stdlib es
:mod:`sky_claw.app.security.links` (módulo de ``main``), la primitiva canónica
de detección de enlaces, reutilizada sin modificarla.

Follow-up registrado: ``FOLLOW_UP_DEDUP_AFTER_PR493`` — cuando el PR #493
aterrice en main, evaluar unificar el digest de árbol con
``sky_claw/local/tools/artifact_digest.py``; hasta entonces este paquete se
mantiene independiente.
"""

from __future__ import annotations

from sky_claw.local.runtime_vault.clone import (
    create_runtime_clone,
    verify_physical_independence,
)
from sky_claw.local.runtime_vault.golden import (
    verify_critical_files,
    verify_golden_master,
)
from sky_claw.local.runtime_vault.golden_protection_plan import (
    DuplicateFileIdError,
    GoldenProtectionNodeKind,
    GoldenProtectionPlan,
    GoldenProtectionPlanError,
    GoldenProtectionPlanState,
    GoldenProtectionSealChecks,
    NodeSecurityBackup,
    PlanCreationError,
    SealedGoldenProtectionPlan,
    SecurityBackupIntegrityError,
    prepare_golden_protection_plan,
    seal_golden_protection_plan,
)
from sky_claw.local.runtime_vault.inventory import inventory_tree
from sky_claw.local.runtime_vault.locking import destination_lock
from sky_claw.local.runtime_vault.models import (
    CriticalFileEvidence,
    CriticalFileExpectation,
    DestinationExistsError,
    FileIdentity,
    GoldenMasterCandidate,
    GoldenMasterDescriptor,
    GoldenMasterVerificationResult,
    InventoryError,
    InventoryLinkError,
    PhysicalIndependenceResult,
    RuntimeCloneDescriptor,
    RuntimeCloneError,
    RuntimeCloneResult,
    RuntimeIdentity,
    RuntimeVaultError,
    RuntimeVerificationResult,
    TreeDigest,
    TreeVerificationResult,
    VerificationState,
)
from sky_claw.local.runtime_vault.node_evidence import (
    NativeEvidenceError,
    NativeEvidenceUnsupportedError,
    NativeNodeEvidence,
    file_id_128_to_int,
    probe_node_evidence,
)
from sky_claw.local.runtime_vault.planning_orchestrator import (
    GP2PlanningDisposition,
    GP2Result,
    orchestrate_golden_protection_planning,
)
from sky_claw.local.runtime_vault.protection import (
    GoldenProtectionEvidence,
    GoldenProtectionInputError,
    GoldenProtectionResult,
    GoldenProtectionRight,
    GoldenProtectionState,
    NodeProtectionObservation,
    classify_protection,
    inspect_golden_protection,
)
from sky_claw.local.runtime_vault.quiescence import (
    DEFAULT_BASE_BACKOFF_SECONDS,
    ERROR_SHARING_VIOLATION,
    MAX_PROBE_RETRIES,
    PROBE_CREATION_DISPOSITION,
    PROBE_DIR_DESIRED_ACCESS,
    PROBE_FILE_DESIRED_ACCESS,
    PROBE_FLAGS,
    PROBE_SHARE_MODE,
    QuiescenceError,
    QuiescenceUnsupportedError,
    QuiescenceViolationError,
    default_quiescence_jitter,
    probe_node_quiescence,
    probe_tree_quiescence,
)
from sky_claw.local.runtime_vault.target_dacl import (
    AUTHENTICATED_USERS_SID,
    BUILTIN_ADMINISTRATORS_SID,
    DIR_TARGET_MASK_AUTHENTICATED_USERS,
    DIR_TARGET_MASK_OWNER_RIGHTS,
    FILE_TARGET_MASK_AUTHENTICATED_USERS,
    FILE_TARGET_MASK_OWNER_RIGHTS,
    LOCAL_SYSTEM_SID,
    OWNER_RIGHTS_SID,
    TARGET_MASK_FULL_ACCESS,
    TargetAceSpec,
    TargetDaclApplyError,
    TargetDaclBuildError,
    TargetDaclError,
    TargetDaclRestoreError,
    TargetDaclSpec,
    TargetDaclUnsupportedError,
    TargetDaclVerificationError,
    TargetDaclVerificationResult,
    apply_target_dacl_by_handle,
    build_native_target_dacl,
    build_target_dacl_spec,
    close_security_handle,
    open_node_security_handle,
    restore_security_descriptor_by_handle,
    verify_restored_security_descriptor_by_handle,
    verify_target_dacl_by_handle,
)
from sky_claw.local.runtime_vault.trusted_namespace import (
    CANONICAL_NAMESPACE_OWNER,
    CANONICAL_NAMESPACE_PRIMARY_GROUP,
    CREATOR_OWNER_SID,
    PERMITTED_NAMESPACE_OWNERS,
    AncestorProvisioningError,
    NamespaceAceSpec,
    NamespaceDaclSpec,
    NamespaceObjectInfo,
    NamespaceObjectNotDirectoryError,
    NamespaceOwnerNotPermittedError,
    NamespaceReparsePointError,
    PreexistingTrustedRegistryError,
    TrustedNamespaceError,
    TrustedNamespaceResult,
    TrustedNamespaceUnsupportedError,
    apply_canonical_tgr_file_security,
    bootstrap_trusted_namespace,
    build_namespace_dacl_spec,
    inspect_namespace_object,
)
from sky_claw.local.runtime_vault.trusted_registry import (
    TrustedGoldenEntry,
    TrustedGoldenMismatchError,
    TrustedGoldenNotFoundError,
    TrustedGoldenRegistry,
    TrustedRegistryDuplicateError,
    TrustedRegistryError,
    TrustedRegistryParseError,
    TrustedRegistrySchemaError,
    TrustedRegistryUnsupportedError,
    deserialize_trusted_golden_registry,
    load_trusted_golden_registry,
    serialize_trusted_golden_registry,
    verify_trusted_golden_binding,
    write_trusted_registry_atomically,
)
from sky_claw.local.runtime_vault.verification import (
    tree_digest_from_files,
    verify_runtime_identity,
    verify_tree,
)

__all__ = [
    "AUTHENTICATED_USERS_SID",
    "AncestorProvisioningError",
    "BUILTIN_ADMINISTRATORS_SID",
    "CANONICAL_NAMESPACE_OWNER",
    "CANONICAL_NAMESPACE_PRIMARY_GROUP",
    "CREATOR_OWNER_SID",
    "CriticalFileEvidence",
    "CriticalFileExpectation",
    "DEFAULT_BASE_BACKOFF_SECONDS",
    "DIR_TARGET_MASK_AUTHENTICATED_USERS",
    "DIR_TARGET_MASK_OWNER_RIGHTS",
    "DestinationExistsError",
    "DuplicateFileIdError",
    "ERROR_SHARING_VIOLATION",
    "FILE_TARGET_MASK_AUTHENTICATED_USERS",
    "FILE_TARGET_MASK_OWNER_RIGHTS",
    "FileIdentity",
    "GP2PlanningDisposition",
    "GP2Result",
    "GoldenMasterCandidate",
    "GoldenMasterDescriptor",
    "GoldenMasterVerificationResult",
    "GoldenProtectionEvidence",
    "GoldenProtectionInputError",
    "GoldenProtectionNodeKind",
    "GoldenProtectionPlan",
    "GoldenProtectionPlanError",
    "GoldenProtectionPlanState",
    "GoldenProtectionResult",
    "GoldenProtectionRight",
    "GoldenProtectionSealChecks",
    "GoldenProtectionState",
    "InventoryError",
    "InventoryLinkError",
    "LOCAL_SYSTEM_SID",
    "MAX_PROBE_RETRIES",
    "NamespaceAceSpec",
    "NamespaceDaclSpec",
    "NamespaceObjectInfo",
    "NamespaceObjectNotDirectoryError",
    "NamespaceOwnerNotPermittedError",
    "NamespaceReparsePointError",
    "NativeEvidenceError",
    "NativeEvidenceUnsupportedError",
    "NativeNodeEvidence",
    "NodeProtectionObservation",
    "NodeSecurityBackup",
    "OWNER_RIGHTS_SID",
    "PERMITTED_NAMESPACE_OWNERS",
    "PROBE_CREATION_DISPOSITION",
    "PROBE_DIR_DESIRED_ACCESS",
    "PROBE_FILE_DESIRED_ACCESS",
    "PROBE_FLAGS",
    "PROBE_SHARE_MODE",
    "PhysicalIndependenceResult",
    "PlanCreationError",
    "PreexistingTrustedRegistryError",
    "QuiescenceError",
    "QuiescenceUnsupportedError",
    "QuiescenceViolationError",
    "RuntimeCloneDescriptor",
    "RuntimeCloneError",
    "RuntimeCloneResult",
    "RuntimeIdentity",
    "RuntimeVaultError",
    "RuntimeVerificationResult",
    "SealedGoldenProtectionPlan",
    "SecurityBackupIntegrityError",
    "TARGET_MASK_FULL_ACCESS",
    "TargetAceSpec",
    "TargetDaclApplyError",
    "TargetDaclBuildError",
    "TargetDaclError",
    "TargetDaclRestoreError",
    "TargetDaclSpec",
    "TargetDaclUnsupportedError",
    "TargetDaclVerificationError",
    "TargetDaclVerificationResult",
    "TreeDigest",
    "TreeVerificationResult",
    "TrustedGoldenEntry",
    "TrustedGoldenMismatchError",
    "TrustedGoldenNotFoundError",
    "TrustedGoldenRegistry",
    "TrustedNamespaceError",
    "TrustedNamespaceResult",
    "TrustedNamespaceUnsupportedError",
    "TrustedRegistryDuplicateError",
    "TrustedRegistryError",
    "TrustedRegistryParseError",
    "TrustedRegistrySchemaError",
    "TrustedRegistryUnsupportedError",
    "VerificationState",
    "apply_canonical_tgr_file_security",
    "apply_target_dacl_by_handle",
    "bootstrap_trusted_namespace",
    "build_namespace_dacl_spec",
    "build_native_target_dacl",
    "build_target_dacl_spec",
    "classify_protection",
    "close_security_handle",
    "create_runtime_clone",
    "default_quiescence_jitter",
    "deserialize_trusted_golden_registry",
    "destination_lock",
    "file_id_128_to_int",
    "inspect_golden_protection",
    "inspect_namespace_object",
    "inventory_tree",
    "load_trusted_golden_registry",
    "open_node_security_handle",
    "orchestrate_golden_protection_planning",
    "prepare_golden_protection_plan",
    "probe_node_evidence",
    "probe_node_quiescence",
    "probe_tree_quiescence",
    "restore_security_descriptor_by_handle",
    "seal_golden_protection_plan",
    "serialize_trusted_golden_registry",
    "tree_digest_from_files",
    "verify_critical_files",
    "verify_golden_master",
    "verify_physical_independence",
    "verify_restored_security_descriptor_by_handle",
    "verify_runtime_identity",
    "verify_target_dacl_by_handle",
    "verify_tree",
    "verify_trusted_golden_binding",
    "write_trusted_registry_atomically",
]
